const CATALOG={
"mammal-sanda-khoumra":{name:"Mammal Sanda & Khoumra — Versace Inspired",amount:19500},
"khoumra-inspired":{name:"Khoumra — Versace Inspired",amount:22000},
"sandal-bukhor-oud":{name:"Sandal Bukhor with Oud",amount:22000},
"royal-sandal-anfar":{name:"Royal Sandal & Anfar",amount:16500},
"liban-sandal":{name:"Liban with Sandal",amount:6500},
"mahlab-delka":{name:"Mahlab Delka",amount:6500},
"normal-delka":{name:"Normal Delka",amount:6000},
"musk-khomra":{name:"Musk Khomra",amount:13500},
"french-cloth-perfume":{name:"French Cloth Perfume — 200ml",amount:10500}
};
function cors(origin,allowed){const ok=origin===allowed||origin==="https://www.sonaincenses.com";return{"Access-Control-Allow-Origin":ok?origin:allowed,"Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type","Vary":"Origin"}}
export default{async fetch(request,env){const url=new URL(request.url),allowed=env.ALLOWED_ORIGIN||"https://sonaincenses.com",headers=cors(request.headers.get("Origin")||allowed,allowed);if(request.method==="OPTIONS")return new Response(null,{status:204,headers});if(url.pathname!=="/create-checkout-session"||request.method!=="POST")return Response.json({error:"Not found"},{status:404,headers});if(!env.STRIPE_SECRET_KEY)return Response.json({error:"Stripe is not configured."},{status:500,headers});try{const body=await request.json(),items=Array.isArray(body.items)?body.items:[];if(!items.length||items.length>20)throw new Error("Your bag is empty or invalid.");const form=new URLSearchParams();form.set("mode","payment");form.set("success_url",allowed+"/success.html?session_id={CHECKOUT_SESSION_ID}");form.set("cancel_url",allowed+"/cancel.html");form.set("billing_address_collection","auto");form.set("phone_number_collection[enabled]","true");["AE","SA","KW","QA","BH","OM"].forEach((c,i)=>form.set("shipping_address_collection[allowed_countries]["+i+"]",c));form.set("allow_promotion_codes","true");if(body.locale==="ar")form.set("locale","ar");if(env.STRIPE_SHIPPING_RATE_ID)form.set("shipping_options[0][shipping_rate]",env.STRIPE_SHIPPING_RATE_ID);items.forEach((item,i)=>{const p=CATALOG[item.id],q=Number(item.quantity);if(!p||!Number.isInteger(q)||q<1||q>10)throw new Error("Invalid product or quantity.");form.set("line_items["+i+"][price_data][currency]","aed");form.set("line_items["+i+"][price_data][unit_amount]",String(p.amount));form.set("line_items["+i+"][price_data][product_data][name]",p.name);form.set("line_items["+i+"][quantity]",String(q))});const stripe=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{"Authorization":"Bearer "+env.STRIPE_SECRET_KEY,"Content-Type":"application/x-www-form-urlencoded"},body:form});const data=await stripe.json();if(!stripe.ok)throw new Error(data&&data.error&&data.error.message||"Stripe could not start checkout.");return Response.json({url:data.url},{headers})}catch(e){return Response.json({error:e.message||"Checkout failed."},{status:400,headers})}}};